#!/bin/bash
 echo ""
 echo "    /_\   _ __   ___ (_)| |__  | |  ___ "
 echo "   //_\\  | '_ \ / __|| || '_ \ | | / _ \                                                  auth: [ vishnu.u@cloud2scale.com ]" 
 echo "  // - \\ |_| | ||___/|_||_.__/ |_| \__| "
 echo ""
 echo "-------------------------------------------"
whoami=`whoami`
path=/home/$whoami/Ansible_automation
home=/home/$whoami

 echo ""
#sudo chmod +x aansible
#sudo cp aansible /usr/bin

#function
check()
     {  
 echo "  Checking for configurations..."     
  if [ -d "$path" ]
   then
    true
   else
    mkdir $path
  fi

 echo "  Checking for playbook..."
 echo "  Please holdon"
 sleep 1
file1=$path/ansible.cfg
file2=$path/hosts_pkg
file3=$path/pkg.yml
f1name=ansible.cfg
f2name=hosts_pkg
f3name=pkg.yml
        
  if [ -f "$file1" ]
   then
    true
   else
    echo "  [warning: $f1name not found]"
    echo "  Updating $f1name"
    echo ""
    wget https://raw.githubusercontent.com/vishnuunni/wget/master/ansible.cfg -P $path
    echo "  [warning: Updated $f1name]"
  fi

  if [ -f "$file2" ]
   then
    true
   else
    echo "  [warning: $f2name not found]"
    echo "  Updating $f2name"
    echo ""
    wget https://raw.githubusercontent.com/vishnuunni/wget/master/hosts_pkg -P $path
    echo ""
    echo "  [warning: Updated $f2name]"
  fi

  if [ -f "$file3" ]
   then
    true
   else
    echo "  [warning: $f3name not found]"
    echo "  Updating $f3name"
    echo ""
    wget https://raw.githubusercontent.com/vishnuunni/wget/master/pkg.yml -P $path
    echo ""
    echo "  [warning: Updated $f3name]"
  fi

  if [[ (-f "$file1" && -f "$file2" && -f "$file3") ]];
   then
    echo "  Play configurations found..."
   else
    echo "  Configurations not updating                                                      [error!]"
    echo "  Provide needed file under $path                                                  [exit]"
   exit
  fi

     }

pkg_install()
     {
 echo > $path/pkg.yml
 echo "---" >> $path/pkg.yml
 echo "- hosts: hosts_pkg" >> $path/pkg.yml
 echo "  become: yes" >> $path/pkg.yml
 echo "  gather_facts: no" >> $path/pkg.yml
 echo "" >> $path/pkg.yml
 echo "" >> $path/pkg.yml
 echo "  tasks:" >> $path/pkg.yml
 echo "         - name: Install $pkg" >> $path/pkg.yml
 echo "           apt: name=$pkg state=latest" >> $path/pkg.yml
     }

#front----------
#echo " ----------------------------------------"
 echo ""
 echo "     Welcome : $whoami"
 sleep 1
 echo ""
 echo ""
 echo "  Checking for Ansible configurations"

  if [ -f "$path/ansible.cfg" ]
   then
    true
   else
    mkdir $path
    echo "  Ansible.cfg not found !      [warning]"
    echo "  Creating one...              [OK]" 
    touch $path/ansible.cfg
    echo ""
    echo "[defaults]" >> $path/ansible.cfg
    echo "private_key_file = $home/c2s_ssh" >> $path/ansible.cfg
    echo "host_key_checking = False." >> $path/ansible.cfg
    echo "remote_user = c2s" >> $path/ansible.cfg
    echo "become = True" >> $path/ansible.cfg
    echo "become_user = root" >> $path/ansible.cfg
    echo "  Done with configuration"
  fi

 sleep 1
 echo ""
 echo "  Checking for c2s_sshkey..."
 sleep 1
  if [ -f "$home/c2s_sshkey" ]
   then 
    echo "  Key found..."
    true
   else
    echo "  Updating key.."
    wget https://raw.githubusercontent.com/vishnuunni/wget/master/c2s_sshkey -P $home
    echo "  Key Updated"
  fi

 sleep 1
 echo ""
 echo "  1. Package Install"
 echo "  2. File Transfer"
 echo "  3. <none>"
 echo ""
 echo -n "  Enter an option : "
 read ipt1
  if [ $ipt1 = 1 ]
   then
    echo "  Package install selected                                                     [OK]"
    check
    echo ""
    echo -n "  Enter the package name : "
    read pkg
    echo -n "  Proceed with '$pkg' installation ? [y/n] :"
    read input
  if [ $input = "y" ]
   then
       echo "  Proceeding with $pkg installation"
      else
       echo "  Cancelled"
       echo ""
       sleep 1
      exit
     fi

if [ -d "$path" ]
then
true
else
mkdir $path
fi
cd $path
echo ""

#echo -n "  Do you have a host file already [y/n]?"
#read hosty
#if [ $hosty = y ]
#then
#echo -n "  Enter the file name here : "
#read hostfile
# if [ -f "$hostfile" ]
# then
# true
# else
# echo "  File not Found..."
# fi
#else

echo -n "  Please enter the server ip you want to trigger : "
read ip
echo > $path/hosts_pkg
echo "[hosts_pkg]" >> $path/hosts_pkg
echo "" >> $path/hosts_pkg
echo "$ip" >> $path/hosts_pkg
echo -n "  Do you want to enter more ip's [y/n]? : "
read y
if [ $y = y ]
then
echo "  Opening the file..."
sleep 1
vi $path/hosts_pkg
sleep 1
echo "  Proceeding..."
else
echo "  Proceeding..."
fi

pkg_install
ansible-playbook -i hosts_pkg pkg.yml

else
echo "  Invalid Option !"
echo "  Exiting..."
echo ""
exit
fi

